import { z } from 'zod';

// Public, bundle-safe environment values. These are injected by Expo at build
// time from `.env.local` (generated by `npm run env:sync` from `.secret`).
//
// Only EXPO_PUBLIC_* values are ever embedded into the mobile bundle.
const envSchema = z.object({
  EXPO_PUBLIC_SUPABASE_URL: z.string().url(),
  EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY: z.string().min(10),
  EXPO_PUBLIC_WEB_API_BASE_URL: z.string().url(),
});

function readEnv() {
  const parsed = envSchema.safeParse({
    EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
    EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
      process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    EXPO_PUBLIC_WEB_API_BASE_URL: process.env.EXPO_PUBLIC_WEB_API_BASE_URL,
  });

  if (!parsed.success) {
    const missing = parsed.error.issues.map((i) => i.path.join('.')).join(', ');
    throw new Error(
      `Eksik veya geçersiz ortam değişkenleri: ${missing}. ` +
        '`npm run env:sync` çalıştırıp .env.local oluşturduğunuzdan emin olun.'
    );
  }

  return parsed.data;
}

export const env = readEnv();
